# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0a0ec26a2b0988ff6a532c0eb047fa44310c4a64eb42924cea5e3666ab1b9aa1e07018043d1bf62935a99bdd89c06d6bb6790b55ca52c5011c46a1508f064383

test:
  secret_key_base: 9c4340baacf7c37863c1e1d50390d834cdb4fd95ed7668f0049b6dab09d4b890c8ea3ffa8dbb8f13744c44227b29ac192a9b2545319b5526a490455478026fb9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
